# Generated by Django 3.2.4 on 2021-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('number_of_games', models.IntegerField()),
                ('total_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('game', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
