# Generated by Django 3.2.4 on 2021-09-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='player',
        ),
    ]
