# Generated by Django 3.2.4 on 2021-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_data_number_of_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='number_of_games',
            field=models.IntegerField(),
        ),
    ]
